import { render, screen } from '@testing-library/react';
import App from './App';

// import rest
import { rest } from 'msw';

import { setupServer } from 'msw/node';
import PokemonList from './component/PokemonList';
import userEvent from '@testing-library/user-event';

const pokemon = {
  count: 801,
  page: 1,
  perPage: 20,
  sort: {
    by: '_id',
    direction: 'asc',
  },
  search: {
    pokemon: '',
  },
  results: [
    {
      _id: '5ff4fb7cd89993a89cc6544f',
      pokemon: 'butterfree',
      id: 16,
      species_id: 12,
      height: 11,
      weight: 320,
      base_experience: 178,
      type_1: 'bug',
      type_2: 'flying',
      attack: 45,
      defense: 50,
      hp: 60,
      special_attack: 90,
      special_defense: 80,
      speed: 70,
      ability_1: 'compound-eyes',
      ability_2: 'NA',
      ability_hidden: 'tinted-lens',
      color_1: '#A8B820',
      color_2: '#A890F0',
      color_f: '#A8AE52',
      egg_group_1: 'bug',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
      generation_id: 1,
      evolves_from_species_id: '11',
      evolution_chain_id: 4,
      shape_id: 13,
      shape: 'bug-wings',
      pokebase: 'butterfree',
      pokedex: 'http://www.pokemon.com/us/pokedex/butterfree',
    },
    {
      _id: '5ff4fb7cd89993a89cc65444',
      pokemon: 'venusaur-mega',
      id: 4,
      species_id: 3,
      height: 24,
      weight: 1555,
      base_experience: 281,
      type_1: 'grass',
      type_2: 'poison',
      attack: 100,
      defense: 123,
      hp: 80,
      special_attack: 122,
      special_defense: 120,
      speed: 80,
      ability_1: 'thick-fat',
      ability_2: 'NA',
      ability_hidden: 'NA',
      color_1: '#78C850',
      color_2: '#A040A0',
      color_f: '#81A763',
      egg_group_1: 'monster',
      egg_group_2: 'plant',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/003_f2.png',
      generation_id: 'NA',
      evolves_from_species_id: 'NA',
      evolution_chain_id: 'NA',
      shape_id: 'NA',
      shape: 'NA',
      pokebase: 'venusaur',
      pokedex: 'http://www.pokemon.com/us/pokedex/venusaur',
    },
    {
      _id: '5ff4fb7cd89993a89cc65454',
      pokemon: 'pidgeotto',
      id: 22,
      species_id: 17,
      height: 11,
      weight: 300,
      base_experience: 122,
      type_1: 'normal',
      type_2: 'flying',
      attack: 60,
      defense: 55,
      hp: 63,
      special_attack: 50,
      special_defense: 50,
      speed: 71,
      ability_1: 'keen-eye',
      ability_2: 'tangled-feet',
      ability_hidden: 'big-pecks',
      color_1: '#A8A878',
      color_2: '#A890F0',
      color_f: '#A8A295',
      egg_group_1: 'flying',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png',
      generation_id: 1,
      evolves_from_species_id: '16',
      evolution_chain_id: 6,
      shape_id: 9,
      shape: 'wings',
      pokebase: 'pidgeotto',
      pokedex: 'http://www.pokemon.com/us/pokedex/pidgeotto',
    },
    {
      _id: '5ff4fb7cd89993a89cc6545d',
      pokemon: 'arbok',
      id: 30,
      species_id: 24,
      height: 35,
      weight: 650,
      base_experience: 153,
      type_1: 'poison',
      type_2: 'NA',
      attack: 85,
      defense: 69,
      hp: 60,
      special_attack: 65,
      special_defense: 79,
      speed: 80,
      ability_1: 'intimidate',
      ability_2: 'shed-skin',
      ability_hidden: 'unnerve',
      color_1: '#A040A0',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'dragon',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png',
      generation_id: 1,
      evolves_from_species_id: '23',
      evolution_chain_id: 9,
      shape_id: 2,
      shape: 'squiggle',
      pokebase: 'arbok',
      pokedex: 'http://www.pokemon.com/us/pokedex/arbok',
    },
    {
      _id: '5ff4fb7cd89993a89cc6545e',
      pokemon: 'pikachu',
      id: 31,
      species_id: 25,
      height: 4,
      weight: 60,
      base_experience: 112,
      type_1: 'electric',
      type_2: 'NA',
      attack: 55,
      defense: 40,
      hp: 35,
      special_attack: 50,
      special_defense: 50,
      speed: 90,
      ability_1: 'static',
      ability_2: 'NA',
      ability_hidden: 'lightning-rod',
      color_1: '#F8D030',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'fairy',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
      generation_id: 1,
      evolves_from_species_id: '172',
      evolution_chain_id: 10,
      shape_id: 8,
      shape: 'quadruped',
      pokebase: 'pikachu',
      pokedex: 'http://www.pokemon.com/us/pokedex/pikachu',
    },
    {
      _id: '5ff4fb7cd89993a89cc6546a',
      pokemon: 'clefairy',
      id: 41,
      species_id: 35,
      height: 6,
      weight: 75,
      base_experience: 113,
      type_1: 'fairy',
      type_2: 'NA',
      attack: 45,
      defense: 48,
      hp: 70,
      special_attack: 60,
      special_defense: 65,
      speed: 35,
      ability_1: 'cute-charm',
      ability_2: 'magic-guard',
      ability_hidden: 'friend-guard',
      color_1: '#EE99AC',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'fairy',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png',
      generation_id: 1,
      evolves_from_species_id: '173',
      evolution_chain_id: 14,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'clefairy',
      pokedex: 'http://www.pokemon.com/us/pokedex/clefairy',
    },
    {
      _id: '5ff4fb7cd89993a89cc6546e',
      pokemon: 'jigglypuff',
      id: 45,
      species_id: 39,
      height: 5,
      weight: 55,
      base_experience: 95,
      type_1: 'normal',
      type_2: 'fairy',
      attack: 45,
      defense: 20,
      hp: 115,
      special_attack: 45,
      special_defense: 25,
      speed: 20,
      ability_1: 'cute-charm',
      ability_2: 'competitive',
      ability_hidden: 'friend-guard',
      color_1: '#A8A878',
      color_2: '#EE99AC',
      color_f: '#B8A484',
      egg_group_1: 'fairy',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png',
      generation_id: 1,
      evolves_from_species_id: '174',
      evolution_chain_id: 16,
      shape_id: 12,
      shape: 'humanoid',
      pokebase: 'jigglypuff',
      pokedex: 'http://www.pokemon.com/us/pokedex/jigglypuff',
    },
    {
      _id: '5ff4fb7cd89993a89cc65482',
      pokemon: 'charmeleon',
      id: 6,
      species_id: 5,
      height: 11,
      weight: 190,
      base_experience: 142,
      type_1: 'fire',
      type_2: 'NA',
      attack: 64,
      defense: 58,
      hp: 58,
      special_attack: 80,
      special_defense: 65,
      speed: 80,
      ability_1: 'blaze',
      ability_2: 'NA',
      ability_hidden: 'solar-power',
      color_1: '#F08030',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'monster',
      egg_group_2: 'dragon',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
      generation_id: 1,
      evolves_from_species_id: '4',
      evolution_chain_id: 2,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'charmeleon',
      pokedex: 'http://www.pokemon.com/us/pokedex/charmeleon',
    },
    {
      _id: '5ff4fb7cd89993a89cc6548d',
      pokemon: 'alakazam',
      id: 71,
      species_id: 65,
      height: 15,
      weight: 480,
      base_experience: 225,
      type_1: 'psychic',
      type_2: 'NA',
      attack: 50,
      defense: 45,
      hp: 55,
      special_attack: 135,
      special_defense: 95,
      speed: 120,
      ability_1: 'synchronize',
      ability_2: 'inner-focus',
      ability_hidden: 'magic-guard',
      color_1: '#F85888',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'humanshape',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png',
      generation_id: 1,
      evolves_from_species_id: '64',
      evolution_chain_id: 27,
      shape_id: 12,
      shape: 'humanoid',
      pokebase: 'alakazam',
      pokedex: 'http://www.pokemon.com/us/pokedex/alakazam',
    },
    {
      _id: '5ff4fb7cd89993a89cc65497',
      pokemon: 'magnemite',
      id: 89,
      species_id: 81,
      height: 3,
      weight: 60,
      base_experience: 65,
      type_1: 'electric',
      type_2: 'steel',
      attack: 35,
      defense: 70,
      hp: 25,
      special_attack: 95,
      special_defense: 55,
      speed: 45,
      ability_1: 'magnet-pull',
      ability_2: 'sturdy',
      ability_hidden: 'analytic',
      color_1: '#F8D030',
      color_2: '#B8B8D0',
      color_f: '#E8CA56',
      egg_group_1: 'mineral',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png',
      generation_id: 1,
      evolves_from_species_id: 'NA',
      evolution_chain_id: 34,
      shape_id: 4,
      shape: 'arms',
      pokebase: 'magnemite',
      pokedex: 'http://www.pokemon.com/us/pokedex/magnemite',
    },
    {
      _id: '5ff4fb7cd89993a89cc654a1',
      pokemon: 'geodude',
      id: 81,
      species_id: 74,
      height: 4,
      weight: 200,
      base_experience: 60,
      type_1: 'rock',
      type_2: 'ground',
      attack: 80,
      defense: 100,
      hp: 40,
      special_attack: 30,
      special_defense: 30,
      speed: 20,
      ability_1: 'rock-head',
      ability_2: 'sturdy',
      ability_hidden: 'sand-veil',
      color_1: '#B8A038',
      color_2: '#E0C068',
      color_f: '#C1A743',
      egg_group_1: 'mineral',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png',
      generation_id: 1,
      evolves_from_species_id: 'NA',
      evolution_chain_id: 31,
      shape_id: 4,
      shape: 'arms',
      pokebase: 'geodude',
      pokedex: 'http://www.pokemon.com/us/pokedex/geodude',
    },
    {
      _id: '5ff4fb7cd89993a89cc654b7',
      pokemon: 'chansey',
      id: 122,
      species_id: 113,
      height: 11,
      weight: 346,
      base_experience: 395,
      type_1: 'normal',
      type_2: 'NA',
      attack: 5,
      defense: 5,
      hp: 250,
      special_attack: 35,
      special_defense: 105,
      speed: 50,
      ability_1: 'natural-cure',
      ability_2: 'serene-grace',
      ability_hidden: 'healer',
      color_1: '#A8A878',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'fairy',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png',
      generation_id: 1,
      evolves_from_species_id: '440',
      evolution_chain_id: 51,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'chansey',
      pokedex: 'http://www.pokemon.com/us/pokedex/chansey',
    },
    {
      _id: '5ff4fb7cd89993a89cc65456',
      pokemon: 'pidgeot',
      id: 23,
      species_id: 18,
      height: 15,
      weight: 395,
      base_experience: 216,
      type_1: 'normal',
      type_2: 'flying',
      attack: 80,
      defense: 75,
      hp: 83,
      special_attack: 70,
      special_defense: 70,
      speed: 101,
      ability_1: 'keen-eye',
      ability_2: 'tangled-feet',
      ability_hidden: 'big-pecks',
      color_1: '#A8A878',
      color_2: '#A890F0',
      color_f: '#A8A295',
      egg_group_1: 'flying',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png',
      generation_id: 1,
      evolves_from_species_id: '17',
      evolution_chain_id: 6,
      shape_id: 9,
      shape: 'wings',
      pokebase: 'pidgeot',
      pokedex: 'http://www.pokemon.com/us/pokedex/pidgeot',
    },
    {
      _id: '5ff4fb7cd89993a89cc65459',
      pokemon: 'raticate',
      id: 26,
      species_id: 20,
      height: 7,
      weight: 185,
      base_experience: 145,
      type_1: 'normal',
      type_2: 'NA',
      attack: 81,
      defense: 60,
      hp: 55,
      special_attack: 50,
      special_defense: 70,
      speed: 97,
      ability_1: 'run-away',
      ability_2: 'guts',
      ability_hidden: 'hustle',
      color_1: '#A8A878',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png',
      generation_id: 1,
      evolves_from_species_id: '19',
      evolution_chain_id: 7,
      shape_id: 8,
      shape: 'quadruped',
      pokebase: 'raticate',
      pokedex: 'http://www.pokemon.com/us/pokedex/raticate',
    },
    {
      _id: '5ff4fb7cd89993a89cc65463',
      pokemon: 'sandslash',
      id: 34,
      species_id: 28,
      height: 10,
      weight: 295,
      base_experience: 158,
      type_1: 'ground',
      type_2: 'NA',
      attack: 100,
      defense: 110,
      hp: 75,
      special_attack: 45,
      special_defense: 55,
      speed: 65,
      ability_1: 'sand-veil',
      ability_2: 'NA',
      ability_hidden: 'sand-rush',
      color_1: '#E0C068',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png',
      generation_id: 1,
      evolves_from_species_id: '27',
      evolution_chain_id: 11,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'sandslash',
      pokedex: 'http://www.pokemon.com/us/pokedex/sandslash',
    },
    {
      _id: '5ff4fb7cd89993a89cc65468',
      pokemon: 'clefable',
      id: 42,
      species_id: 36,
      height: 13,
      weight: 400,
      base_experience: 217,
      type_1: 'fairy',
      type_2: 'NA',
      attack: 70,
      defense: 73,
      hp: 95,
      special_attack: 95,
      special_defense: 90,
      speed: 60,
      ability_1: 'cute-charm',
      ability_2: 'magic-guard',
      ability_hidden: 'unaware',
      color_1: '#EE99AC',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'fairy',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png',
      generation_id: 1,
      evolves_from_species_id: '35',
      evolution_chain_id: 14,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'clefable',
      pokedex: 'http://www.pokemon.com/us/pokedex/clefable',
    },
    {
      _id: '5ff4fb7cd89993a89cc65480',
      pokemon: 'growlithe',
      id: 64,
      species_id: 58,
      height: 7,
      weight: 190,
      base_experience: 70,
      type_1: 'fire',
      type_2: 'NA',
      attack: 70,
      defense: 45,
      hp: 55,
      special_attack: 70,
      special_defense: 50,
      speed: 60,
      ability_1: 'intimidate',
      ability_2: 'flash-fire',
      ability_hidden: 'justified',
      color_1: '#F08030',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png',
      generation_id: 1,
      evolves_from_species_id: 'NA',
      evolution_chain_id: 25,
      shape_id: 8,
      shape: 'quadruped',
      pokebase: 'growlithe',
      pokedex: 'http://www.pokemon.com/us/pokedex/growlithe',
    },
    {
      _id: '5ff4fb7cd89993a89cc65481',
      pokemon: 'primeape',
      id: 63,
      species_id: 57,
      height: 10,
      weight: 320,
      base_experience: 159,
      type_1: 'fighting',
      type_2: 'NA',
      attack: 105,
      defense: 60,
      hp: 65,
      special_attack: 60,
      special_defense: 70,
      speed: 95,
      ability_1: 'vital-spirit',
      ability_2: 'anger-point',
      ability_hidden: 'defiant',
      color_1: '#C03028',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png',
      generation_id: 1,
      evolves_from_species_id: '56',
      evolution_chain_id: 24,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'primeape',
      pokedex: 'http://www.pokemon.com/us/pokedex/primeape',
    },
    {
      _id: '5ff4fb7cd89993a89cc65485',
      pokemon: 'poliwhirl',
      id: 67,
      species_id: 61,
      height: 10,
      weight: 200,
      base_experience: 135,
      type_1: 'water',
      type_2: 'NA',
      attack: 65,
      defense: 65,
      hp: 65,
      special_attack: 50,
      special_defense: 50,
      speed: 90,
      ability_1: 'water-absorb',
      ability_2: 'damp',
      ability_hidden: 'swift-swim',
      color_1: '#6890F0',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'water1',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png',
      generation_id: 1,
      evolves_from_species_id: '60',
      evolution_chain_id: 26,
      shape_id: 12,
      shape: 'humanoid',
      pokebase: 'poliwhirl',
      pokedex: 'http://www.pokemon.com/us/pokedex/poliwhirl',
    },
    {
      _id: '5ff4fb7cd89993a89cc65488',
      pokemon: 'abra',
      id: 69,
      species_id: 63,
      height: 9,
      weight: 195,
      base_experience: 62,
      type_1: 'psychic',
      type_2: 'NA',
      attack: 20,
      defense: 15,
      hp: 25,
      special_attack: 105,
      special_defense: 55,
      speed: 90,
      ability_1: 'synchronize',
      ability_2: 'inner-focus',
      ability_hidden: 'magic-guard',
      color_1: '#F85888',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'humanshape',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png',
      generation_id: 1,
      evolves_from_species_id: 'NA',
      evolution_chain_id: 27,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'abra',
      pokedex: 'http://www.pokemon.com/us/pokedex/abra',
    },
  ],
};

const server = setupServer(
  rest.get('https://pokedex-alchemy.herokuapp.com/api/pokedex', (req, res, ctx) => {
    return res(ctx.json(pokemon));
  })
);

beforeAll(() => server.listen());

afterAll(() => server.close());

test('Pokemons renders on page', async () => {
  render(<App />);

  const heading = await screen.findByRole('heading', {
    name: /pokemon/i,
  });
  const pokemons = await screen.findAllByRole('listitem');
  expect(heading).toBeInTheDocument();
  expect(pokemons).toHaveLength(20);
});

test('testing for filter by type of pokemon', async () => {
  render(<App />);

  const dropdown = await screen.findByRole('combobox');
  userEvent.selectOptions(dropdown, 'bug');

  expect(screen.getByRole('option', { name: 'Bug' }).selected).toBe(true);
});

test('searchbar loads pokemons', async () => {
  render(<App />);

  const searchbar = await screen.findByRole('textbox');
  const searchbutton = screen.getByRole('button');
  const pokemonName = 'pidgeotto';

  const pokemonlist = await screen.findAllByText(pokemonName, { exact: false });
  const resultNames = pokemonlist.map((pokemon) => pokemon.textContent);

  const nameCheck = (name) => name.includes(pokemonName);

  const hasSameName = resultNames.every(nameCheck);
  expect(hasSameName).toBe(true);

  userEvent.type(searchbar, pokemonName);

  expect(searchbar).toBeInTheDocument();
  expect(searchbutton).toBeInTheDocument();
});
